apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: hybrid-todo     
  namespace: todo-app  
spec:
  selector:
    matchExpressions:
      - key: app  
        operator: In
        values:
        - hybrid-todo-aws
        - hybrid-todo-google
