apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: todo     
  namespace: todo-app  
spec:
  selector:
    matchExpressions:
      - key: app  
        operator: In
        values:
        - todo
        - hybrid-todo-secret
  componentKinds:
  - group: app.ibm.com/v1alpha1
    kind: Subscription
