apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: todo
  name: prod-only
  namespace: todo-app
spec:
  clusterSelector:
    matchLabels:
      env: production