apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: todo              
  namespace: todo-app
  labels:
    app: todo
spec:
  channel:  simple-app/federation
  placement: 
    placementRef: 
      kind: PlacementRule
      name: prod-only     
