---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: prod-only-aws
  namespace: todo-app
spec:
  clusterSelector:
    matchLabels:
      env: production-aws
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: prod-only-google
  namespace: todo-app
spec:
  clusterSelector:
    matchLabels:
      env: production-google