---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: hybrid-todo-secret
  namespace: hybrid-todo-secret
  labels:
    app: hybrid-todo-secret
spec:
  channel: acm-app-secrets/hybrid-todo-secret
  packageFilter:
    annotations:
      secretname: hybrid-todo-secret
  placement:
    placementRef:
      kind: PlacementRule
      name: todo-secret-placement