---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: acs-init-secrets
  namespace: todo-app
  labels:
    app: hybrid-todo
spec:
  channel: init-bundle-ch/acs-init-secrets
  placement:
    placementRef:
      kind: PlacementRule
      name: acs-init-secrets
