---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: acs-init-secrets
  namespace: acm-app-secrets
spec:
  type: Namespace
  pathname: acs-init-secrets
  sourceNamespaces:
    - acm-app-secrets
