---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  annotations:
    secretname: hybrid-todo-secret
  name: todo-secret-placement
  namespace: acm-app-secrets
spec:
  clusterSelector:
    matchLabels:
      'encironment': 'production'