---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: todo-app-secret
  namespace: todo-app
  labels:
    app: todo-app
spec:
  channel: acm-app-secrets/hybrid-todo-secret
  placement:
    placementRef:
      kind: PlacementRule
      name: prod-only