---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: todo-app-secrets
  namespace: todo-app
  labels:
    app: hybrid-todo
spec:
  channel: acm-app-secrets/hybrid-todo-secrets
  placement:
    placementRef:
      kind: PlacementRule
      name: prod-only
