---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  annotations:
    secretname: hybrid-todo-secret
  name: todo-secret-placement
  namespace: todo-app
spec:
  clusterSelector:
    matchLabels:
      'env': 'production'