apiVersion: apps/v1
kind: Deployment
metadata:
  name: hybrid-todo-deployment
  namespace: hybrid-todo
spec:
  selector:
    matchLabels:
      app: hybrid-todo
  replicas: 1
  template:
    metadata:
      labels:
        app: hybrid-todo
    spec:
      containers:
      - name: hybrid-todo
        image: image-registry.openshift-image-registry.svc:5000/hybrid-todo/hybrid-todo@sha256:305aad4400d7e2b8facfa1fcb25813038f51d4c5efc6bba4be1d1aa2fe59930e
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /opt/app-root/src/config/
          name: config-volume
      volumes:
      - secret:
          defaultMode: 420
          secretName: hybrid-todo-secret
        name: config-volume
