apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-db-claim
  namespace: hybrid-todo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
