apiVersion: v1
kind: Secret
metadata:
  name: hybrid-todo-secret
  namespace: acm-app-secrets
stringData:
  run.env: |-
    DB_USER=nbhsfucaqjvffj
    DB_PASSWORD=25d607d74768a6b9a4b6274a3e7ecc1322d1891ad6e708c803d581ba8feb628c
    DB_HOST=ec2-34-255-134-200.eu-west-1.compute.amazonaws.com
    DB_PORT=5432
    DB=dag9j95qaso90i